workflows:
  ios-workflow:
    name: iOS Build - Invoice Baba
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Lokalhunt - API Key
    
    environment:
      vars:
        BUNDLE_ID: com.codevel.invoicebaba
        APP_STORE_APP_ID: 6759199018
      
      node: v20.11.0
      xcode: latest
      cocoapods: default
      
      # Automatic Signing Configuration
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.codevel.invoicebaba
    
    scripts:
      - name: Install npm dependencies
        script: |
          cd app
          rm -rf node_modules package-lock.json
          npm install
      
      - name: Set up environment variables
        script: |
          cd app
          # Create .env file from Codemagic environment variables
          echo "VITE_API_URL=$VITE_API_URL" > .env
          echo "VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID" >> .env
          echo "VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID" >> .env
          echo "VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY" >> .env
      
      - name: Build web app
        script: |
          cd app
          npm run build
      
      - name: Initialize iOS platform
        script: |
          cd app
          # Remove corrupted iOS directory if it exists
          rm -rf ios
          # Add iOS platform fresh
          npx cap add ios
      
      - name: Add GoogleService-Info.plist
        script: |
          cd app
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/App/App/GoogleService-Info.plist
      
      - name: Install CocoaPods dependencies
        script: |
          cd app/ios/App
          pod install
      
      - name: Set up code signing settings on Xcode project
        script: |
          cd app/ios/App
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd app/ios/App
          agvtool new-version -all $BUILD_NUMBER
      
      - name: Build ipa for distribution
        script: |
          cd app/ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App"
    
    artifacts:
      - app/ios/App/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: Android Build - Invoice Baba
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.codevel.invoicebaba"
      node: v20.11.0
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          cd app
          rm -rf node_modules package-lock.json
          npm install
      
      - name: Set up environment variables
        script: |
          cd app
          echo "VITE_API_URL=$VITE_API_URL" > .env
          echo "VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID" >> .env
          echo "VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID" >> .env
          echo "VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY" >> .env
      
      - name: Build web app
        script: |
          cd app
          npm run build
      
      - name: Initialize Android platform
        script: |
          cd app
          rm -rf android
          npx cap add android
      
      - name: Configure Android project
        script: |
          cd app
          
          # Fix variables.gradle — compileSdk/targetSdk 34 for Capacitor 6
          cat > android/variables.gradle << 'EOF'
          ext {
              minSdkVersion = 22
              compileSdkVersion = 34
              targetSdkVersion = 34
              androidxActivityVersion = '1.8.0'
              androidxAppCompatVersion = '1.6.1'
              androidxCoordinatorLayoutVersion = '1.2.0'
              androidxCoreVersion = '1.12.0'
              androidxFragmentVersion = '1.6.2'
              coreSplashScreenVersion = '1.0.1'
              androidxWebkitVersion = '1.8.0'
              junitVersion = '4.13.2'
              androidxJunitVersion = '1.1.5'
              androidxEspressoCoreVersion = '3.5.1'
              cordovaAndroidVersion = '10.1.1'
          }
          EOF
          
          # Fix root build.gradle — AGP 8.2.1, google-services 4.4.2
          cat > android/build.gradle << 'EOF'
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.2.1'
                  classpath 'com.google.gms:google-services:4.4.2'
              }
          }
          
          apply from: "variables.gradle"
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          
          task clean(type: Delete) {
              delete rootProject.buildDir
          }
          EOF
          
          # Fix Gradle wrapper version for AGP 8.7.3
          # Keep Gradle 8.2.1 (compatible with AGP 8.2.1 and Java 17)
          
          # Fix package name in app/build.gradle
          sed -i 's/namespace "com\..*"/namespace "com.codevel.invoicebaba"/' android/app/build.gradle
          sed -i 's/applicationId "com\..*"/applicationId "com.codevel.invoicebaba"/' android/app/build.gradle
          
          # Fix strings.xml
          cat > android/app/src/main/res/values/strings.xml << 'EOF'
          <?xml version='1.0' encoding='utf-8'?>
          <resources>
              <string name="app_name">Invoice Baba</string>
              <string name="title_activity_main">Invoice Baba</string>
              <string name="package_name">com.codevel.invoicebaba</string>
              <string name="custom_url_scheme">com.codevel.invoicebaba</string>
          </resources>
          EOF
          
          # Fix Java package directory
          mkdir -p android/app/src/main/java/com/codevel/invoicebaba
          cat > android/app/src/main/java/com/codevel/invoicebaba/MainActivity.java << 'EOF'
          package com.codevel.invoicebaba;
          
          import com.getcapacitor.BridgeActivity;
          
          public class MainActivity extends BridgeActivity {}
          EOF
          rm -rf android/app/src/main/java/com/invoicebaba 2>/dev/null || true
      
      - name: Generate app icons
        script: |
          cd app
          node scripts/generate-android-icons.mjs
      
      - name: Add google-services.json
        script: |
          cd app
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      
      - name: Sync Capacitor
        script: |
          cd app
          npx cap sync android
      
      - name: Set up local.properties
        script: |
          cd app/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      
      - name: Build Android release (AAB + APK)
        script: |
          cd app/android
          ./gradlew bundleRelease
          ./gradlew assembleRelease
    
    artifacts:
      - app/android/app/build/outputs/**/*.aab
      - app/android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - javalead.venkatesh@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
