// Color Palettes — 5 base palettes used across all 20 layout families
// Each palette provides primary, light, dark, and derived colors

export const PALETTES = {
  charcoal: {
    key: 'charcoal',
    family: 'black',
    primary: '#374151',
    primaryLight: '#F3F4F6',
    primaryDark: '#111827',
    primaryMuted: '#9CA3AF',
    headerText: '#FFFFFF',
    headerTextMuted: '#D1D5DB',
    text: '#1F2937',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    altRowBg: '#FAFAFA',
    tableHeaderBg: '#F3F4F6',
    tableHeaderText: '#374151',
    badgeBg: '#F3F4F6',
    badgeText: '#374151',
  },
  crimson: {
    key: 'crimson',
    family: 'red',
    primary: '#DC2626',
    primaryLight: '#FEF2F2',
    primaryDark: '#991B1B',
    primaryMuted: '#FCA5A5',
    headerText: '#FFFFFF',
    headerTextMuted: '#FECDD3',
    text: '#1F2937',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    altRowBg: '#FAFAFA',
    tableHeaderBg: '#FEF2F2',
    tableHeaderText: '#DC2626',
    badgeBg: '#FEF2F2',
    badgeText: '#DC2626',
  },
  ocean: {
    key: 'ocean',
    family: 'blue',
    primary: '#2563EB',
    primaryLight: '#DBEAFE',
    primaryDark: '#1D4ED8',
    primaryMuted: '#93C5FD',
    headerText: '#FFFFFF',
    headerTextMuted: '#BFDBFE',
    text: '#1F2937',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    altRowBg: '#FAFAFA',
    tableHeaderBg: '#EFF6FF',
    tableHeaderText: '#2563EB',
    badgeBg: '#DBEAFE',
    badgeText: '#1D4ED8',
  },
  forest: {
    key: 'forest',
    family: 'green',
    primary: '#047857',
    primaryLight: '#ECFDF5',
    primaryDark: '#065F46',
    primaryMuted: '#6EE7B7',
    headerText: '#FFFFFF',
    headerTextMuted: '#A7F3D0',
    text: '#1F2937',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    altRowBg: '#FAFAFA',
    tableHeaderBg: '#ECFDF5',
    tableHeaderText: '#047857',
    badgeBg: '#ECFDF5',
    badgeText: '#065F46',
  },
  royal: {
    key: 'royal',
    family: 'purple',
    primary: '#7C3AED',
    primaryLight: '#F5F3FF',
    primaryDark: '#6D28D9',
    primaryMuted: '#C4B5FD',
    headerText: '#FFFFFF',
    headerTextMuted: '#DDD6FE',
    text: '#1F2937',
    textLight: '#6B7280',
    textMuted: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    altRowBg: '#FAFAFA',
    tableHeaderBg: '#F5F3FF',
    tableHeaderText: '#7C3AED',
    badgeBg: '#F5F3FF',
    badgeText: '#6D28D9',
  },
}

export const PALETTE_LIST = Object.values(PALETTES)
export const PALETTE_KEYS = Object.keys(PALETTES)
