/**
 * Document Type Defaults
 * 
 * Each document type defines:
 * - labels: UI labels for form sections, fields, and buttons
 * - fields: visibility flags for optional sections/columns
 * 
 * Business-level overrides (stored in Business.documentTypeConfig JSON)
 * are deep-merged on top of these defaults at runtime.
 */

export const DOCUMENT_TYPE_DEFAULTS = {
  invoice: {
    key: 'invoice',
    label: 'Invoice',
    heading: 'INVOICE',
    prefix: 'INV-',
    labels: {
      fromSection: 'From',
      toSection: 'Bill To',
      numberField: 'Invoice #',
      dateField: 'Invoice Date',
      saveButton: 'Save Invoice',
      descriptionCol: 'Description',
      unitPriceCol: 'Unit Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: true,
      showDueDate: true,
      showPoNumber: true,
      showQty: true,
      showUnitPrice: true,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'full', // full | basic | simple
    },
  },

  tax_invoice: {
    key: 'tax_invoice',
    label: 'Tax Invoice',
    heading: 'TAX INVOICE',
    prefix: 'TINV-',
    labels: {
      fromSection: 'From',
      toSection: 'Bill To',
      numberField: 'Invoice #',
      dateField: 'Invoice Date',
      saveButton: 'Save Tax Invoice',
      descriptionCol: 'Description',
      unitPriceCol: 'Unit Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: true,
      showDueDate: true,
      showPoNumber: true,
      showQty: true,
      showUnitPrice: true,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'full',
    },
  },

  proforma: {
    key: 'proforma',
    label: 'Proforma Invoice',
    heading: 'PROFORMA INVOICE',
    prefix: 'PI-',
    labels: {
      fromSection: 'Sent By',
      toSection: 'Sent To',
      numberField: 'Invoice #',
      dateField: 'Invoice Date',
      saveButton: 'Save Proforma Invoice',
      descriptionCol: 'Description',
      unitPriceCol: 'Unit Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: false,
      showShipTo: true,
      showDueDate: true,
      showPoNumber: true,
      showQty: true,
      showUnitPrice: true,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'full',
    },
  },

  receipt: {
    key: 'receipt',
    label: 'Receipt',
    heading: 'RECEIPT',
    prefix: 'RCT-',
    labels: {
      fromSection: 'From',
      toSection: 'Bill To',
      numberField: 'Receipt #',
      dateField: 'Receipt Date',
      saveButton: 'Save Receipt',
      descriptionCol: 'Description',
      unitPriceCol: 'Unit Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: false,
      showShipTo: true,
      showDueDate: true,
      showPoNumber: true,
      showQty: true,
      showUnitPrice: true,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'full',
    },
  },

  sales_receipt: {
    key: 'sales_receipt',
    label: 'Sales Receipt',
    heading: 'SALES RECEIPT',
    prefix: 'SR-',
    labels: {
      fromSection: 'From',
      toSection: 'Sold To',
      numberField: 'Receipt #',
      dateField: 'Receipt Date',
      saveButton: 'Save Sales Receipt',
      descriptionCol: 'Description',
      unitPriceCol: 'Unit Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: false,
      showShipTo: true,
      showDueDate: true,
      showPoNumber: true,
      showQty: true,
      showUnitPrice: true,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'full',
    },
  },

  cash_receipt: {
    key: 'cash_receipt',
    label: 'Cash Receipt',
    heading: 'CASH RECEIPT',
    prefix: 'CR-',
    labels: {
      fromSection: 'Received By',
      toSection: 'Received From',
      numberField: 'No.',
      dateField: 'Date',
      saveButton: 'Save Cash Receipt',
      descriptionCol: 'Description',
      unitPriceCol: 'Amount',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: false,
      showTerms: false,
      showSignature: true,
      showNotes: false,
      showPaymentMethod: true,
      lineItemsLayout: 'simple',
    },
  },

  quote: {
    key: 'quote',
    label: 'Quote',
    heading: 'QUOTE',
    prefix: 'QT-',
    labels: {
      fromSection: 'From',
      toSection: 'Bill To',
      numberField: 'Quote #',
      dateField: 'Quote Date',
      saveButton: 'Save Quote',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },

  estimate: {
    key: 'estimate',
    label: 'Estimate',
    heading: 'ESTIMATE',
    prefix: 'EST-',
    labels: {
      fromSection: 'From',
      toSection: 'Bill To',
      numberField: 'Estimate #',
      dateField: 'Estimate Date',
      saveButton: 'Save Estimate',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },

  credit_memo: {
    key: 'credit_memo',
    label: 'Credit Memo',
    heading: 'CREDIT MEMO',
    prefix: 'CM-',
    labels: {
      fromSection: 'From',
      toSection: 'Customer',
      numberField: 'Credit Memo #',
      dateField: 'Credit Memo Date',
      saveButton: 'Save Credit Memo',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },

  credit_note: {
    key: 'credit_note',
    label: 'Credit Note',
    heading: 'CREDIT NOTE',
    prefix: 'CN-',
    labels: {
      fromSection: 'From',
      toSection: 'Customer',
      numberField: 'Credit Note #',
      dateField: 'Credit Note Date',
      saveButton: 'Save Credit Note',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },

  purchase_order: {
    key: 'purchase_order',
    label: 'Purchase Order',
    heading: 'PURCHASE ORDER',
    prefix: 'PO-',
    labels: {
      fromSection: 'From',
      toSection: 'Vendor',
      numberField: 'Purchase Order #',
      dateField: 'Purchase Order Date',
      saveButton: 'Save Purchase Order',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },

  delivery_note: {
    key: 'delivery_note',
    label: 'Delivery Note',
    heading: 'DELIVERY NOTE',
    prefix: 'DN-',
    labels: {
      fromSection: 'Delivery From',
      toSection: 'Deliver To',
      numberField: 'Delivery Note #',
      dateField: 'Delivery Date',
      saveButton: 'Save Delivery Note',
      descriptionCol: 'Description',
      unitPriceCol: 'Price',
      qtyCol: 'Qty',
      amountCol: 'Amount',
      taxCol: 'Tax',
    },
    fields: {
      showLogo: true,
      showShipTo: false,
      showDueDate: false,
      showPoNumber: false,
      showQty: false,
      showUnitPrice: false,
      showTax: true,
      showTerms: true,
      showSignature: true,
      showNotes: true,
      showPaymentMethod: false,
      lineItemsLayout: 'basic',
    },
  },
}

/**
 * Get the resolved config for a document type, merging business-level overrides.
 * @param {string} typeKey - e.g. 'invoice', 'quote', 'cash_receipt'
 * @param {object|null} businessOverrides - Business.documentTypeConfig JSON (keyed by type)
 * @returns {object} Merged config with labels + fields
 */
export function getDocTypeConfig(typeKey, businessOverrides = null) {
  const defaults = DOCUMENT_TYPE_DEFAULTS[typeKey] || DOCUMENT_TYPE_DEFAULTS.invoice

  if (!businessOverrides || !businessOverrides[typeKey]) {
    return defaults
  }

  const overrides = businessOverrides[typeKey]

  return {
    ...defaults,
    ...(overrides.prefix !== undefined && { prefix: overrides.prefix }),
    ...(overrides.nextNumber !== undefined && { nextNumber: overrides.nextNumber }),
    labels: {
      ...defaults.labels,
      ...(overrides.labels || {}),
    },
    fields: {
      ...defaults.fields,
      ...(overrides.fields || {}),
    },
  }
}
